docs(ref/rst/directives):  fix figure option spelling...
Attempting to use option `:figname:` causes DocUtils to generate an error:

  ERROR: Error in “figure” directive: unknown option: “figname”.

It turns out that the correct spelling for this option is `:name:`.
This is tested with the :numfig: role and works correctly.